server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
    - dependency: "com.github.topi314.lavasearch:lavasearch-plugin:1.0.0"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
    - dependency: "com.github.topi314.lavalyrics:lavalyrics-plugin:1.1.0"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false

plugins:
  lavasrc:
    providers:
      - "dzisrc:%ISRC%"
      - "dzsearch:%QUERY%"
    sources:
      spotify: true
      deezer: true
    lyrics-sources:
      spotify: true
      deezer: true
      lrcLib: true
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID}
      clientSecret: ${SPOTIFY_CLIENT_SECRET}
      countryCode: "US"
      preferAnonymousToken: false
      spDc: ${SPOTIFY_SP_DC}
      customTokenEndpoint: "http://spotify-tokener:8080/api/token"
    deezer:
      masterDecryptionKey: ${DEEZER_KEY}
      arl: ${DEEZER_ARL}
      formats: ["FLAC", "MP3_320", "MP3_256", "MP3_128", "MP3_64", "AAC_64"]
  lavalyrics:
    sources:
      - spotify
      - deezer
      - lrcLib

logging:
  level:
    root: INFO
    lavalink.server.io.RequestLoggingFilter: WARN
    lavalink.server.config.RequestAuthorizationFilter: ERROR
