name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v6

      - name: Build New Image
        run: docker compose build client

      - name: Deploy
        run: bash scripts/deploy.sh

      - name: Cleanup Unused Images
        run: docker image prune -f

      - name: Cleanup Build Cache
        run: docker buildx prune -f --max-used-space=1gb

    env:
      DEEZER_ARL: ${{ secrets.DEEZER_ARL }}
      DEEZER_KEY: ${{ secrets.DEEZER_KEY }}
      DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      COMPOSE_PROJECT_NAME: ${{ secrets.COMPOSE_PROJECT_NAME }}
      INSTANCE: ${{ secrets.INSTANCE }}
      LAVALINK_PASSWORD: ${{ secrets.LAVALINK_PASSWORD }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      MONGODB_COLLECTION_NAME: ${{ secrets.MONGODB_COLLECTION_NAME }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_SP_DC: ${{ secrets.SPOTIFY_SP_DC }}
