name: Kill Docker Container

on: workflow_dispatch

jobs:
  run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Remove Container
        run: docker container rm jace -f

      - name: Cleanup Unused Images
        run: docker image prune -f
