name: Docker Runner

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Run Container
        run: docker compose up -d --build
        env:
          DEEZER_ARL: ${{ secrets.DEEZER_ARL }}
          DEEZER_KEY: ${{ secrets.DEEZER_KEY }}
          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          ENV: ${{ secrets.ENV }}
          MONGODB_COLLECTION_NAME: ${{ secrets.MONGODB_COLLECTION_NAME }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}

      - name: Cleanup Unused Images
        run: docker image prune -f

      - name: Cleanup Build Cache
        run: docker buildx prune -f --max-used-space=10gb
