name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker compose up -d --build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DISCORD_APP_ID: ${{ secrets.DISCORD_APP_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DYNAMODB_DEFAULT_PREFS: ${{ secrets.DYNAMODB_DEFAULT_PREFS }}
          DYNAMODB_GUILD_PREFS: ${{ secrets.DYNAMODB_GUILD_PREFS }}
          DYNAMODB_USER_PREFS: ${{ secrets.DYNAMODB_USER_PREFS }}
          ENV: ${{ secrets.ENV }}
          HEALTH_PORT: ${{ secrets.HEALTH_PORT }}
          YOUTUBE_COOKIE: ${{ secrets.YOUTUBE_COOKIE }}

      - name: Cleanup Unused Images
        run: docker image prune -f

      - name: Cleanup Build Cache
        run: docker builder prune -f --keep-storage 2GB
          
